version: '3'
volumes:
  database:
networks:
  backend_network:
    ipam:
      config:
        - subnet: 172.80.0.1/16
          gateway: 172.80.0.1

services:
  database:
    container_name: database
    image: postgres:latest
    networks:
      backend_network:
        ipv4_address: 172.80.0.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: default
    volumes:
      - database:/var/lib/postgresql/data
  backend:
    container_name: backend
    build: ../cole-enyart-blog-cms-capstone-be
    depends_on:
      - database
    networks:
      backend_network:
        ipv4_address: 172.80.0.3
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    build: ../cole-enyart-blog-cms-capstone-fe
    ports:
      - "3000:80"